name: Deploy with specific client or server version（Rollback)

on:
  workflow_dispatch:
    inputs:
      clientversion:
        description: 'Client Dev Version: vx.x.x or latest'
        required: true
        default: 'latest'
        type: string
      serverversion:
        description: 'Server Dev Version: vx.x.x or latest'
        required: true
        default: 'latest'
        type: string
 
jobs:
  print_input:
    runs-on: ubuntu-latest
    env:
      CLIENT_VERSION: ${{ github.event.inputs.clientversion }}
      SERVER_VERSION: ${{ github.event.inputs.serverversion }}
    steps:
      - name: print input client and server version
        run: |
          echo "Client version: $CLIENT_VERSION"
          echo "Server version: $SERVER_VERSION"
