name: Add_prod_release_tag

on:
#   release:
#     types: [published]
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Add_prod_release_tag:
    runs-on: ubuntu-latest
    outputs:
       latest_tag: ${{ steps.outputbuild.outputs.latest_tag }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    
    - name: Bump Prod Release Version and Push tag
      id: prod_tag_verison 
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        release_branches: main
        # fetch_all_tags: true
        # DRY_RUN: true
        tag_prefix: r
    
    # - name: Create a GitHub release
    #   uses: ncipollo/release-action@v1

    - name: Check output
      id: outputbuild    
      env: 
        RELEASE_VERSION: ${{ steps.prod_tag_verison.outputs.tag }}
      run: echo "latest_tag=$RELEASE_VERSION" >> $GITHUB_OUTPUT