name: Release Workflow

on:
  release:
    types: [published,released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release tag name
        run: echo "The release tag is ${{ github.event.release.tag_name }}"