name: Release Workflow

on:
  release:
    types: [published]
  workflow_dispatch: # manual
    inputs:
      release_version:
        required: true
        default: 'latest'
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      INPUT_TAG: ${{ github.event.inputs.release_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release tag name
        run: echo "The release tag is $RELEASE_TAG"

      - name: Get input release tag version
        run: echo "The input release version is $INPUT_TAG"
        