name: Release Workflow

on:
  release:
    types: [published]
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RELEASE_VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release tag name
        run: echo "The release tag is ${{ RELEASE_VERSION }}"