name: Release Workflow

on:
  release:
    types: [published]
  workflow_dispatch: # manual
    inputs:
      release_version:
        required: true
        default: 'latest'
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      INPUT_TAG: ${{ github.event.inputs.release_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release tag version
        run: |
          if [ -z "$RELEASE_TAG" ]; then
            echo "The release tag variale is empty"
          else
            echo "The release tag is: $RELEASE_TAG"
          fi

      - name: Get input release tag version
        run: |
          if [ -z "$INPUT_TAG" ]; then
            echo "The manual input tag variale is empty"
          else
            echo "The manual input tag is: $INPUT_TAG"
          fi

      - name: Assign release tag version
        run: |
          if [ -z "$RELEASE_TAG" ] && [ -n "$INPUT_TAG" ]; then
            echo "release tag version: $INPUT_TAG"
          elif [ -n "$RELEASE_TAG" ] && [ -z "$INPUT_TAG" ]; then
            echo "release tag version: $RELEASE_TAG"
          else
            echo "No Avaiable release tag version"
            exit 1
          fi

        

      
        