name: upper-images

on:
  push:
    paths:
      - ".github/workflows/upper-images.yml"
      - "upper/**"
  workflow_dispatch: # manual

permissions:
  packages: write
  contents: read # not needed in public repos

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker image build -t upper .
        working-directory: ./upper
      - name: test it
        run: docker container run upper hello wes
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # Chao-Xi
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag upper ghcr.io/chao-xi/upper:latest
      - run: docker tag upper ghcr.io/chao-xi/upper:${{ github.ref_name }}
      - run: docker push ghcr.io/chao-xi/upper:latest
      - run: docker push ghcr.io/chao-xi/upper:${{ github.ref_name }}
  
  scan:
    runs-on: ubuntu-latest
    needs: image
    steps:
      - name: checkout 
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Docker Scout Quickview and CVEs
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: ghcr.io/chao-xi/upper:latest

